from collections import namedtuple
from PyDictionary import PyDictionary

dictionary = PyDictionary()

Word = namedtuple("Word", ["word", "definition"])

words = [
    Word(word="Rill", definition=None),
    Word(word="Anon", definition=None),
    Word(word="Sophistry", definition=None),
    Word(word="Stile", definition=None),
    Word(word="Flume", definition=None),
    Word(word="Fain", definition=None),
    Word(word="Bill of fare", definition="A menu. The selection of food available. A program for a theatrical event."),
    Word(word="Lignite", definition=None),
    Word(word="Canticle", definition=None),
    Word(word="Spile", definition=None),
    Word(word="Syce", definition="A servant employed to look after horses, drive carriages, etc. In old India."),
    Word(word="Tasset", definition=None),
    Word(word="Philately", definition=None),
    Word(word="Zizith", definition="the 613 fringes of thread, symbolizing the 613 commandments in the Hebrew Scriptures, formerly worn at the corners of the shawl-like garment known as a tallith."),
    Word(word="Yare", definition="(of a ship) responding promptly to the helm; easily manageable."),
    Word(word="Acerbic", definition=None),
    Word(word="Dais", definition=None),
    Word(word="Loggia", definition=None),
    Word(word="Filigree", definition=None),
    Word(word="Incipient", definition=None),
    Word(word="Atelier", definition=None),
    Word(word="Garnet", definition=None),
    Word(word="Moire", definition=None),
    Word(word="Undercroft", definition="The crypt of a church."),
    Word(word="Sobriquet", definition=None),
    Word(word="Fete", definition=None),
    Word(word="Fetid", definition=None),
    Word(word="Temerity", definition=None),
    Word(word="Quire", definition=None),
    Word(word="Alacrity", definition=None),
    Word(word="Chorister", definition=None),
    Word(word="Chromophage", definition="A timesink. An eater of time. French."),
    Word(word="Missive", definition=None),
    Word(word="Marquetry", definition=None),
    Word(word="Lorica", definition=None),
    Word(word="Profligate", definition=None),
    # Word(word="Vaporetto", definition=None),
    # Word(word="Tresses", definition=None),
    # Word(word="Newel", definition=None),
    # Word(word="Arcade", definition=None),
    # Word(word="Naiad", definition=None),
    # Word(word="Fiat", definition=None),
    # Word(word="Dias", definition=None),
    # Word(word="Folio", definition=None),
    # Word(word="Inchoate", definition=None),
    # Word(word="Discomfit", definition=None),
    # Word(word="Recrimination", definition=None),
    # Word(word="Gossamer", definition=None),
    # Word(word="Convalescent", definition=None),
    # Word(word="Cassock", definition=None),
    # Word(word="Wiggy", definition=None),
    # Word(word="Invidious", definition=None),
    # Word(word="Recondite", definition=None),
    # Word(word="Integument", definition=None),
    # Word(word="Grise", definition=None),
    # Word(word="Clinker", definition=None),
    # Word(word="Head frame", definition=None),
    # Word(word="Sheave wheel", definition=None),
    # Word(word="Rive", definition=None),
    # Word(word="Beribboned", definition=None),
    # Word(word="Tensegrity", definition=None),
    # Word(word="Foraminifera", definition=None),
    # Word(word="Bolide", definition=None),
    # Word(word="Ensconce", definition=None),
    # Word(word="Melange", definition=None),
    # Word(word="Supine", definition=None),
    # Word(word="Petechia", definition=None),
    # Word(word="Tatterdemalion", definition=None),
    # Word(word="Nadir", definition=None),
    # Word(word="Empennage", definition=None),
    # Word(word="Anhydrous", definition=None),
    # Word(word="Shirty", definition=None),
    # Word(word="Metempsychosis", definition=None),
    # Word(word="Sutra", definition=None),
    # Word(word="Ineluctable", definition=None),
    # Word(word="Autochthonous", definition=None),
    # Word(word="Svelte", definition=None),
    # Word(word="Hoi Polloi", definition=None),
    # Word(word="Hackles", definition=None),
    # Word(word="Dalliance", definition=None),
    # Word(word="Kaffeeklatsch", definition=None),
    # Word(word="Clodhopper", definition=None),
    # Word(word="Abrogate", definition=None),
    # Word(word="Ken", definition=None),
    # Word(word="Legerdemain", definition=None),
    # Word(word="Remora", definition=None),
    # Word(word="Libration Point", definition=None),
    # Word(word="Inquest", definition=None),
    # Word(word="Fief", definition=None),
    # Word(word="Lee", definition=None),
    # Word(word="Aegis", definition=None),
    # Word(word="Dragoon", definition=None),
    # Word(word="Bandied", definition=None),
    # Word(word="Auger", definition=None),
    # Word(word="Lambent", definition=None),
    # Word(word="Troika", definition=None),
    # Word(word="Rattan", definition=None),
    # Word(word="Insuperable", definition=None),
    # Word(word="Inimical", definition=None),
    # Word(word="Proletariat", definition=None),
    # Word(word="Pellucid", definition=None),
    # Word(word="Scarified", definition=None),
    # Word(word="Dint", definition=None),
    # Word(word="Specious", definition=None),
    # Word(word="Cudgel", definition=None),
    # Word(word="Claque", definition=None),
    # Word(word="Mutatis Mutandis", definition=None),
    # Word(word="Pip", definition=None),
    # Word(word="Festooned", definition=None),
    # Word(word="Sosie", definition=None),
    # Word(word="Flagon", definition=None),
    # Word(word="Laving", definition=None),
    # Word(word="Coquetry", definition=None),
    # Word(word="Scrivener", definition=None),
    # Word(word="Enmity", definition=None),
    # Word(word="Signet", definition=None),
    # Word(word="Dervish", definition=None),
    # Word(word="Internecine", definition=None),
    # Word(word="Corvid", definition=None),
    # Word(word="Hied", definition=None),
    # Word(word="Cadge", definition=None),
    # Word(word="Rookery", definition=None),
    # Word(word="Skein", definition=None),
    # Word(word="Wattle", definition=None),
    # Word(word="Askance", definition=None),
    # Word(word="Obloquy", definition=None),
    # Word(word="Clabbering", definition=None),
    # Word(word="Hoary", definition=None),
    # Word(word="Debouch", definition=None),
    # Word(word="Antideluvian", definition=None),
    # Word(word="Minatory", definition=None),
    # Word(word="Barbican", definition=None),
    # Word(word="Tropopause", definition=None),
    # Word(word="Trysts", definition=None),
    # Word(word="Gainsay", definition=None),
    # Word(word="Littoral", definition=None),
    # Word(word="Presaging", definition=None),
    # Word(word="Bitt", definition=None),
    # Word(word="Mollified", definition=None),
    # Word(word="Junket", definition=None),
    # Word(word="Cairn", definition=None),
    # Word(word="Peroration", definition=None),
    # Word(word="Eleemosynary", definition=None),
    # Word(word="Peloton", definition=None),
    # Word(word="RDX", definition=None),
    # Word(word="Fait", definition=None),
    # Word(word="Fait accompli", definition=None),
    # Word(word="Sycophantic", definition=None),
    # Word(word="Indolent", definition=None),
    # Word(word="Heather", definition=None),
    # Word(word="Sough", definition=None),
    # Word(word="Dun", definition=None),
    # Word(word="Sump", definition=None),
    # Word(word="Cloyed", definition=None),
    # Word(word="Meerschaum", definition=None),
    # Word(word="Dahurian Larch", definition=None),
    # Word(word="Cadre", definition=None),
    # Word(word="Limpid", definition=None),
    # Word(word="Dais", definition=None),
    # Word(word="Ura Sedge", definition=None),
    # Word(word="Saltation", definition=None),
    # Word(word="Chiton", definition=None),
    # Word(word="Libertine", definition=None),
    # Word(word="Syzygy", definition=None),
    # Word(word="Propitious", definition=None),
    # Word(word="Mien", definition=None),
    # Word(word="Emolument", definition=None),
    # Word(word="Starling", definition=None),
    # Word(word="Bailey", definition=None),
    # Word(word="Doolapse", definition=None),
    # Word(word="Recalcitrant", definition=None),
    # Word(word="Cols", definition=None),
    # Word(word="Loess", definition=None),
    # Word(word="Imprecations", definition=None),
    # Word(word="Redolent", definition=None),
    # Word(word="Gammon", definition=None),
    # Word(word="Effusive", definition=None),
    # Word(word="Carouse", definition=None),
    # Word(word="Catalepsy", definition=None),
    # Word(word="Excoriating", definition=None),
    # Word(word="Latchet", definition=None),
    # Word(word="Funny Farm", definition=None),
    # Word(word="Acrophobia", definition=None),
    # Word(word="Spate", definition=None),
    # Word(word="Epistolary", definition=None),
    # Word(word="Potsherds", definition=None),
    # Word(word="Cultivar", definition=None),
    # Word(word="Phosphene", definition=None),
    # Word(word="Malingerer", definition=None),
    # Word(word="Craven", definition=None),
    # Word(word="Inured", definition=None),
    # Word(word="Maudlin", definition=None),
    # Word(word="Bole", definition=None),
    # Word(word="Apoplectic", definition=None),
    # Word(word="Gregarious", definition=None),
    # Word(word="Lanolin", definition=None),
    # Word(word="Exculpation", definition=None),
    # Word(word="Pseudopodia", definition=None),
    # Word(word="Duff", definition=None),
    # Word(word="Simpered", definition=None),
    # Word(word="Fulminate", definition=None),
    # Word(word="Lector", definition=None),
    # Word(word="Puerile", definition=None),
    # Word(word="Demography", definition=None),
    # Word(word="Propound", definition=None),
    # Word(word="Wormwood", definition=None),
    # Word(word="Docent", definition=None),
    # Word(word="Shibboleth", definition=None),
    # Word(word="Dilettante", definition=None),
    # Word(word="Bellicose", definition=None),
    # Word(word="Festschrift", definition=None),
    # Word(word="Castigated", definition=None),
    # Word(word="Peccadillo", definition=None),
    # Word(word="Winnow", definition=None),
    # Word(word="Brackish", definition=None),
    # Word(word="Legerdemain", definition=None),
    # Word(word="Antisepsis", definition=None),
    # Word(word="Apposite", definition=None),
    # Word(word="Obeisance", definition=None),
    # Word(word="Euphonious", definition=None),
    # Word(word="Effluvium", definition=None),
]

def dict_get_fallbacks(d, keys):
    for key in keys:
        if key in d:
            return d[key]
    raise ValueError("object has none of the keys: {}\n{}".format(keys, d))

def beef_up_word(word):
    print "+ {}".format(word)
    if word.definition == None:
        m = dictionary.meaning(word.word)
        print m
        x = dict_get_fallbacks(m, ["Noun", "Verb", "Adjective", "Adverb"])[0]
        word = word._replace(definition=x)
        print "Filled '{}': '{}'".format(word.word, x)
    return word

words = map(beef_up_word, words)

if __name__ == '__main__':
    for w in words:
        print w
